/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.customer_one_system;

import com.abc.JDBCConnection.ConnectionClass;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;

/**
 *
 * @author test
 */
public class AccountSetup extends javax.swing.JFrame {

    /**
     * Creates new form AccountSetup
     */
    boolean isAccoutGiven = false;

    public AccountSetup() {
        initComponents();
        isAccoutGiven = false;
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate = LocalDate.now();
        lblOpeningDateOut.setText((String) dtf.format(localDate));
    }
    int custID;

    AccountSetup(int custID) throws ClassNotFoundException, SQLException {
        initComponents();
        this.custID = custID;
        isAccoutGiven = true;
        Connection connect = ConnectionClass.getConnected();
        Statement statement = connect.createStatement();
        String query = "select preferred_acc_1, opening_date from customer where customer_id=" + custID + " ";
        ResultSet rs = statement.executeQuery(query);
        int accNo;
        if (rs.next()) {
            accNo = rs.getInt(1);
            txtAccountNo.setText(Integer.toString(accNo));
            lblOpeningDateOut.setText(rs.getString(2).substring(0, 10));
        }

    }

    AccountSetup(int custID, boolean b) throws ClassNotFoundException, SQLException {
        initComponents();
        this.custID=custID;
        isAccoutGiven = b;
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate = LocalDate.now();
        lblOpeningDateOut.setText((String) dtf.format(localDate));
        Connection connect = ConnectionClass.getConnected();
        Statement statement = connect.createStatement();
        String query="select account_num_seq.nextval from dual";
        ResultSet rs = statement.executeQuery(query);
        rs.next();
        txtAccountNo.setText(Integer.toString(rs.getInt(1)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblOpenDate = new javax.swing.JLabel();
        cmboType = new javax.swing.JComboBox<>();
        rdoStatus = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtBalance = new javax.swing.JTextField();
        lblOpeningDateOut = new javax.swing.JLabel();
        btnAddAccount = new javax.swing.JButton();
        txtAccountNo = new javax.swing.JTextField();
        lblMsg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Setup Accout");

        lblAccNo.setText("Account Number:");

        lblAccType.setText("Account Type:");

        lblStatus.setText("Status: ");

        lblBalance.setText("Balance:");

        lblOpenDate.setText("OpenDate:");

        cmboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Current", "Salary " }));
        cmboType.setToolTipText("");

        buttonGroup1.add(rdoStatus);
        rdoStatus.setText("Active");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("InActive");

        txtBalance.setText("500.00");

        lblOpeningDateOut.setText("  ");

        btnAddAccount.setText("Add Account");
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });

        txtAccountNo.setText("Automatic Allocation");

        lblMsg.setText(" ");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblOpenDate)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(lblOpeningDateOut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccountNo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStatus)
                            .addComponent(lblAccNo)
                            .addComponent(lblAccType)
                            .addComponent(lblBalance)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnAddAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAccNo)
                    .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccType)
                    .addComponent(cmboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoStatus)
                        .addComponent(jRadioButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpenDate)
                    .addComponent(lblOpeningDateOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lblMsg)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAccount)
                    .addComponent(btnBack))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        lblMsg.setText("");
        try {
            Connection connect = ConnectionClass.getConnected();
            int accNo = 0;
            boolean canProceed = true;
            Double balance = 0.0;
            try {
                balance = Double.parseDouble(txtBalance.getText());
                accNo = Integer.parseInt(txtAccountNo.getText());
            } catch (NumberFormatException e) {
                lblMsg.setText("Invalid data");
                canProceed = false;
            }
            String radioText = null;
            for (Enumeration buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = (AbstractButton) buttons.nextElement();
                if (button.isSelected()) {
                    radioText = button.getText();
                }
            }
            if (radioText == null) {
                lblMsg.setText("Choose a type");
                canProceed = false;
            }
            if (canProceed) {
                String q = "insert into account values (?,?,?,?,"
                        + "to_date(?,'yyyy-mm-dd'),?)";
                PreparedStatement prepStmt = connect.prepareStatement(q);
                prepStmt.setInt(1, accNo);
                prepStmt.setString(2, (String) cmboType.getSelectedItem());
                prepStmt.setString(3, radioText);
                prepStmt.setDouble(4, balance);
                String date= lblOpeningDateOut.getText().trim();
                prepStmt.setString(5,date);
                prepStmt.setInt(6, custID);
                int res = prepStmt.executeUpdate();
                if (res < 1) {
                    lblMsg.setText("Operation faled");
                } else {
                    lblMsg.setText("Sucessfull Transaction");
                    
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountSetup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            new MainMenu().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountSetup.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountSetup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmboType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblOpenDate;
    private javax.swing.JLabel lblOpeningDateOut;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rdoStatus;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtBalance;
    // End of variables declaration//GEN-END:variables
}
