/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.customer_one_system;

import com.abc.JDBCConnection.ConnectionClass;
import static com.abc.customer_one_system.ListOfCustomerRequests.requestType;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author test
 */
public class ChequebookRequest extends javax.swing.JFrame {

    /**
     * Creates new form ChequebookRequest
     */
    public ChequebookRequest() {
        initComponents();
    }
    
    
    public ChequebookRequest(int requestTypeVal, String requestStatus)throws Exception
    {
        initComponents();
        
        Connection con = ConnectionClass.getConnected();
        Statement stmt = con.createStatement();
        String query ="select a.account_number, a.acc_type, c.name, cr.csr_date, cb.no_of_leaves, cr.csr_status, cr.csr_response,cr.csr_id\n" +
                      "from cheque_book_request cb join customer_service_request cr on cr.csr_id = cb.csr_id \n" +
                      "join account a on cr.account_number = a.account_number\n" +
                       "join customer c on c.customer_id = a.customer_id where  cr.csr_status='"+requestStatus+"' and cr.csr_type="+requestTypeVal; 
        
        
        ResultSet rs = stmt.executeQuery(query);
        
        while(rs.next())
        {
            String ac_no = String.valueOf(rs.getLong(1));
            String ac_type = rs.getString(2);
            String cust_name = rs.getString(3);
            String rev_date = rs.getDate(4).toString();
            String leaves = String.valueOf(rs.getInt(5));
            String cb_status = rs.getString(6);
            String cb_response = rs.getString(7);
            ListOfCustomerRequests.csr_id = rs.getInt(8);
            
            lbltxAcNoCsr1.setText(ac_no);
            lbltxAcTypeCsr1.setText(ac_type);
            lbltxCustNameCsr1.setText(cust_name);
            lbltxReqDateCsr1.setText(rev_date);
            lbltxNoOfLeavesCsr1.setText(leaves);
            cmbStatusCsr1.setSelectedItem(cb_status);
            txtareaRejectionCsr1.setText(cb_response);
            
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        lblAcNoCsr1 = new javax.swing.JLabel();
        lbltxAcNoCsr1 = new javax.swing.JLabel();
        lblAcTypeCsr1 = new javax.swing.JLabel();
        lbltxAcTypeCsr1 = new javax.swing.JLabel();
        lblCustNameCsr1 = new javax.swing.JLabel();
        lbltxCustNameCsr1 = new javax.swing.JLabel();
        lblReqDateCsr1 = new javax.swing.JLabel();
        lbltxReqDateCsr1 = new javax.swing.JLabel();
        lblNoOfLeavesCsr1 = new javax.swing.JLabel();
        lbltxNoOfLeavesCsr1 = new javax.swing.JLabel();
        lblStatusCsr1 = new javax.swing.JLabel();
        lblRejectionCsr1 = new javax.swing.JLabel();
        btnSubmitCsr1 = new javax.swing.JButton();
        btnBackCsr1 = new javax.swing.JButton();
        cmbStatusCsr1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaRejectionCsr1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(607, 612));

        lblTitle1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitle1.setText("Chequebook Request");

        lblAcNoCsr1.setText("Account Number");

        lblAcTypeCsr1.setText("Account Type");

        lblCustNameCsr1.setText("Customer Name");

        lblReqDateCsr1.setText("Request Date");

        lblNoOfLeavesCsr1.setText("Number of Leaves");

        lblStatusCsr1.setText("Status");

        lblRejectionCsr1.setText("Reason for Rejection");

        btnSubmitCsr1.setText("Submit");
        btnSubmitCsr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitCsr1ActionPerformed(evt);
            }
        });

        btnBackCsr1.setText("Back");
        btnBackCsr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCsr1ActionPerformed(evt);
            }
        });

        cmbStatusCsr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Rejected", "Processed" }));

        txtareaRejectionCsr1.setColumns(20);
        txtareaRejectionCsr1.setRows(5);
        jScrollPane1.setViewportView(txtareaRejectionCsr1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRejectionCsr1)
                            .addComponent(lblNoOfLeavesCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReqDateCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustNameCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAcTypeCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAcNoCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltxNoOfLeavesCsr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(cmbStatusCsr1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbltxReqDateCsr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbltxAcTypeCsr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbltxAcNoCsr1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                    .addComponent(lbltxCustNameCsr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSubmitCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBackCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAcNoCsr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltxAcNoCsr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAcTypeCsr1)
                    .addComponent(lbltxAcTypeCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCustNameCsr1)
                    .addComponent(lbltxCustNameCsr1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReqDateCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltxReqDateCsr1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNoOfLeavesCsr1)
                    .addComponent(lbltxNoOfLeavesCsr1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatusCsr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusCsr1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRejectionCsr1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitCsr1)
                    .addComponent(btnBackCsr1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackCsr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCsr1ActionPerformed
       // ChequebookRequest chequebookrequest = new ChequebookRequest();
        //chequebookrequest.setVisible(false);
        this.setVisible(false);
        ListOfCustomerRequests listofcustomerrequests = new ListOfCustomerRequests();
        listofcustomerrequests.setVisible(true);
        //System.exit(0);
    }//GEN-LAST:event_btnBackCsr1ActionPerformed

    private void btnSubmitCsr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitCsr1ActionPerformed
        
        int success;
        try {
            Connection con = ConnectionClass.getConnected();
            Statement stmt = con.createStatement();
            String query = "update customer_service_request set csr_status='"+cmbStatusCsr1.getSelectedItem()+"',csr_response='"+txtareaRejectionCsr1.getText()+"'where csr_id="+ListOfCustomerRequests.csr_id;
            
            success = stmt.executeUpdate(query);
            
            if(success>0)
            {
                 JOptionPane.showMessageDialog(null, "Updated Successfully!");
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Error in Updating!\n Try Again!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChequebookRequest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ChequebookRequest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitCsr1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChequebookRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChequebookRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChequebookRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChequebookRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChequebookRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackCsr1;
    private javax.swing.JButton btnSubmitCsr1;
    private javax.swing.JComboBox<String> cmbStatusCsr1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcNoCsr1;
    private javax.swing.JLabel lblAcTypeCsr1;
    private javax.swing.JLabel lblCustNameCsr1;
    private javax.swing.JLabel lblNoOfLeavesCsr1;
    private javax.swing.JLabel lblRejectionCsr1;
    private javax.swing.JLabel lblReqDateCsr1;
    private javax.swing.JLabel lblStatusCsr1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lbltxAcNoCsr1;
    private javax.swing.JLabel lbltxAcTypeCsr1;
    private javax.swing.JLabel lbltxCustNameCsr1;
    private javax.swing.JLabel lbltxNoOfLeavesCsr1;
    private javax.swing.JLabel lbltxReqDateCsr1;
    private javax.swing.JTextArea txtareaRejectionCsr1;
    // End of variables declaration//GEN-END:variables
}
